### ISSUE TITLE
HP ThinPro 7.2 - Cannot start new VPN session

### ISSUE THREAD

**Issue by eminnear** [OpenVPN/openvpn3-linux#161]
_HP ThinPro 7.2 sp13.5_
_Openvpn3/Linux v19_beta_
_Openvpn3 core v3.7.1 linux x86_64 64-bit_

When updating from openvpn3 v18_beta to v19_beta I am now getting the error in the subject when trying to connect using: `openvpn3 session-start --config "profile.ovpn"`
Every other version since v9_beta (started at v9_beta) has worked perfectly with no issues.
I ran `openvpn3-admin version --services` and all services are running v19_beta.
Logging shows the following:
> "Waiting for session to start ...** ERROR ** Failed calling D-Bus method LookupConfigName: Timeout was reached"

I have tried restarting the D-Bus service and re-running but it comes up with the same errors.

**Comment by dsommers** [comment]
Which Linux distribution are you running?

**Comment by eminnear** [comment]
HP ThinPro 7.2 sp13.5 based on Ubuntu 18.04, linux kernel 5.17

**Comment by eminnear** [comment]
This is interesting. Journalctl output on v18_beta vs v19_beta:
> v18_beta: dbus-daemon[1297]: [system] Activating service name='net.openvpn.v3.backends' requested by ':1.89'

Everything works fine with v18_beta using net.openvpn.v3.backends

> v19_beta: dbus-daemon[1297]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service
systemd[1]: Starting Hostname Service...
systemd[4816]: systemd-hostnamed.service: Failed to set up mount namespacing: No such file or directory
systemd[4816]: systemd-hostnamed.service: Failed at step NAMESPACE spawning /lib/systemd/systemd-hostnamed: No such file or directory
systemd[1]: systemd-hostnamed.service: Main process exited, code=exited, status=226/NAMESPACE
systemd[1]: systemd-hostnamed.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Hostname Service.

Obviously fails here as it's trying to use org.freedesktop.hostname1 instead of net.openvpn.v3.backends

**Comment by dsommers** [comment]
Okay, this gives some hints.  v19_beta added [sending more platform info](https://github.com/OpenVPN/openvpn3-linux/commit/7e072365c2f18b7053f65413ce2917dd3de56b3e) to the server (via `IV_PLAT` variables reported in the server log).  It first tries to access the "Hostname Service" (`systemd-hostnamed`) to retrieve all the details.

Not being able to access the "Hostname Service" sounds really odd, but the code in OpenVPN 3 Linux should have a fallback if this fails.  Since the v19_beta release you are the first one to report this issue.

I have no idea what "HP ThinPro" really means in this context, except it sounds like a fork of Ubuntu 18.04. Can you see if you have this service installed, or if you can install it additionally?  On most distros, this service is part of the base systemd package.  You can also check its presence by running this command:

     $ busctl introspect org.freedesktop.hostname1 /org/freedesktop/hostname1

**Comment by eminnear** [comment]
ThinPro is Hewlett Packards Operating system based off of Ubuntu (7.2 is based on 18.04 and newly released 8.0 is based on 20.04). It is mostly for their thin clients, such as the mt21 or mt45 etc thin client laptops. 
`busctl introspect org.freedesktop.hostname1 /org/freedesktop/hostname1`
I get, "Failed to introspect object /org/freedesktop/hostname1 of service org.freedesktop.hostname1: Connection timed out"

**Comment by dsommers** [comment]
Okay, can you try to figure out why the `systemd-hostnamed` (`org.freedesktop.hostname1` service) is missing, and if you can install that?  I will after the Christmas holidays try to figure out why the fallback doesn't work as expected.

I must say it is quite odd that the hostnamed service is lacking, as that's usually considered a integrated part of the systemd stack, for managing the identity and role of the host.

**Comment by eminnear** [comment]
It is installed however it fails every-time it is started. I am guessing HP has another service that replaces it I am just not sure which. Their Thin Pro 8.0 has the systemd-hostnamed service running so looks like they switched to that. I don't think there is anything I can do at this point for Thin Pro 7.2 other than run v18 instead of 19.

**Comment by dsommers** [comment]
If `busctl introspect org.freedesktop.hostname1 /org/freedesktop/hostname1` fails, or any of the commands below ... the `systemd-hostnamed` service is not accessible.

      $ busctl call org.freedesktop.hostname1 /org/freedesktop/hostname1 org.freedesktop.DBus.Properties Get ss org.freedesktop.hostname1 OperatingSystemCPEName
      $ busctl call org.freedesktop.hostname1 /org/freedesktop/hostname1 org.freedesktop.DBus.Properties Get ss org.freedesktop.hostname1 OperatingSystemPrettyName

I've tried to locate an install or docker/podman image with HP ThinPro, without much luck.  If there are no publicly available images to install and test, I am considering to put HP ThinPro on a "not supported" list - which means OpenVPN 3 Linux will only be supported on a best-effort, without any kind of guarantees.

**Comment by eminnear** [comment]
Normally I grab any installs from their HP ThinUpdate Windows applications: HP ThinUpdate releases<https://ftp.ext.hp.com/pub/tcimages/EasyUpdate/ThinUpdate/Win64/>

All versions work perfectly fine up to 18 on HP Thin Pro 7.2.
All versions work perfectly fine up to the latest v19 on HP Thin Pro 8.0 as it does use org.freedesktop.hostname1.


Thank you,

Erich Minnear
IPAP—System Administrator
Office: 920.560.1273  |  Fax: 920.968.5093 | https://ipap.com<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Flinkprotect.cudasvc.com%2Furl%3Fa%3Dhttps%253a%252f%252fipap.com%26c%3DE%2C1%2Coxhds8CCLo-cTwgVSkeGAi8_OsLSLStdZoLk82mld0CIMEc_cf8RNu_zoyaEzinOu1_nxPjv9FB-ifncF4pUdDv3s28Wd24lofHzbmgKrhZ7NZvLq0MP2K8%2C%26typo%3D1&data=05%7C01%7Ceminnear%40ipap.com%7C53cfece5f6134ef3135208da591bf239%7C7a6295a8b69b4fd0a744bb57bad2d825%7C0%7C0%7C637920273827103473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GHliswVKizWbHvuJeuce0QOoQSn3zoRGrRQxgejdW%2F8%3D&reserved=0>


From: David Sommerseth ***@***.***>
Date: Friday, January 6, 2023 at 6:43 PM
To: OpenVPN/openvpn3-linux ***@***.***>
Cc: eminnear ***@***.***>, Author ***@***.***>
Subject: Re: [OpenVPN/openvpn3-linux] Failed to start new session: Connection not ready to connect yet (object does not exist) (Issue #161)
External Mail: This email originated outside IPAP. BEWARE clicking links and opening attachments, when in doubt use the Phish Alert button!


If busctl introspect org.freedesktop.hostname1 /org/freedesktop/hostname1 fails, or any of the commands below ... the systemd-hostnamed service is not accessible.

  $ busctl call org.freedesktop.hostname1 /org/freedesktop/hostname1 org.freedesktop.DBus.Properties Get ss org.freedesktop.hostname1 OperatingSystemCPEName

  $ busctl call org.freedesktop.hostname1 /org/freedesktop/hostname1 org.freedesktop.DBus.Properties Get ss org.freedesktop.hostname1 OperatingSystemPrettyName

I've tried to locate an install or docker/podman image with HP ThinPro, without much luck. If there are no publicly available images to install and test, I am considering to put HP ThinPro on a "not supported" list - which means OpenVPN 3 Linux will only be supported on a best-effort, without any kind of guarantees.

**Comment by dsommers** [comment]
Okay, so those downloads points at Windows binaries .... This is quite a closed environment to work with from the OpenVPN 3 Linux side.

I'm going to close this issue, as HP ThinPro 7.2 clearly is not a functional environment for OpenVPN 3 Linux v19_beta and newer; it deviates too much from ordinary Linux distributions.

As I understand it HP ThinPro 8.0 seems to work with all tested OpenVPN 3 Linux releases (including v19_beta), so that's the only "workaround". The OpenVPN 3 Linux project will not strive for full support on a Linux distribution variant requiring Windows to get it running.

OpenVPN 3 Linux is fully supported on Debian, Fedora, Red Hat Enterprise Linux and Ubuntu releases.  Other Linux distributions will only be on a best-effort basis, like there is a community support for [Arch Linux](https://aur.archlinux.org/packages/openvpn3) and we have done only minor adjustments to have Alpine Linux support.  But as always, certain pre-conditions need to match, like runtime dependencies.  Which means, if OpenVPN 3 Linux works on HP ThinPro 8.0 - then that's the minimum version OpenVPN 3 Linux will run on.

**Comment by eminnear** [comment]
The download is for HP ThinUpdate which is a windows program you install and run to then select which patches or installers you want to download. ThinPro is Linux/Ubuntu based.

Thank you,

Erich Minnear
IPAP—System Administrator
Office: 920.560.1273  |  Fax: 920.968.5093 | https://ipap.com<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Flinkprotect.cudasvc.com%2Furl%3Fa%3Dhttps%253a%252f%252fipap.com%26c%3DE%2C1%2Coxhds8CCLo-cTwgVSkeGAi8_OsLSLStdZoLk82mld0CIMEc_cf8RNu_zoyaEzinOu1_nxPjv9FB-ifncF4pUdDv3s28Wd24lofHzbmgKrhZ7NZvLq0MP2K8%2C%26typo%3D1&data=05%7C01%7Ceminnear%40ipap.com%7C53cfece5f6134ef3135208da591bf239%7C7a6295a8b69b4fd0a744bb57bad2d825%7C0%7C0%7C637920273827103473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GHliswVKizWbHvuJeuce0QOoQSn3zoRGrRQxgejdW%2F8%3D&reserved=0>


From: David Sommerseth ***@***.***>
Date: Friday, January 27, 2023 at 5:12 PM
To: OpenVPN/openvpn3-linux ***@***.***>
Cc: eminnear ***@***.***>, Author ***@***.***>
Subject: Re: [OpenVPN/openvpn3-linux] HP ThinPro 7.2 - Cannot start new VPN session (Issue #161)
External Mail: This email originated outside IPAP. BEWARE clicking links and opening attachments, when in doubt use the Phish Alert button!


Okay, so those downloads points at Windows binaries .... This is quite a closed environment to work with from the OpenVPN 3 Linux side.

I'm going to close this issue, as HP ThinPro 7.2 clearly is not a functional environment for OpenVPN 3 Linux v19_beta and newer; it deviates too much from ordinary Linux distributions.

As I understand it HP ThinPro 8.0 seems to work with all tested OpenVPN 3 Linux releases (including v19_beta), so that's the only "workaround". The OpenVPN 3 Linux project will not strive for full support on a Linux distribution variant requiring Windows to get it running.

OpenVPN 3 Linux is fully supported on Debian, Fedora, Red Hat Enterprise Linux and Ubuntu releases. Other Linux distributions will only be on a best-effort basis, like there is a community support for Arch Linux<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Faur.archlinux.org%2Fpackages%2Fopenvpn3&data=05%7C01%7Ceminnear%40ipap.com%7C614c3267c8444c8730ca08db00bbe5d5%7C7a6295a8b69b4fd0a744bb57bad2d825%7C0%7C0%7C638104579253953620%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7SKC%2B4EG3zqDJi9tpkwZkDVqFsHZrVm0ye1u1vAcr4s%3D&reserved=0> and we have done only minor adjustments to have Alpine Linux support. But as always, certain pre-conditions need to match, like runtime dependencies. Which means, if OpenVPN 3 Linux works on HP ThinPro 8.0 - then that's the minimum version OpenVPN 3 Linux will run on.
